### ISSUE TITLE
[0.11.0.280] Crash after item creation - ClassNotFoundException: net.minecraft.client.audio

### ISSUE THREAD

**Issue by musznik** [MachineMuse/MachineMusePowersuits#608]
1. Power Armor Leggings has been crated
2. When i'm trying to wear them, server crashes
3. Cannot connect to server

*ModularPowersuits-0.11.0.263.jar
*Numina-0.4.0.127.jar
*Launcher/Mod : ATLauncher, ResonantRise Pack

Server Crash Log
```
[16:28:27] [Server thread/INFO] [Waila]: Player EntityPlayerMP['muszak'/382, l='world', x=122,85, y=73,00, z=-47,77] connected. Sending ping
[16:28:27] [Server thread/INFO] [mcjty.rftools.RFTools]: SMP: Player logged in: Sync diminfo to clients
[16:28:27] [Server thread/INFO] [mcjty.rftools.RFTools]: Sync dimension info to clients!
[16:28:27] [Server thread/INFO] [mcjty.rftools.RFTools]: Send validation data to the client
[16:28:30] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingEvent$LivingUpdateEvent@65fb44a3:
java.lang.NoClassDefFoundError: net/minecraft/client/audio/ISound
        at net.machinemuse.numina.sound.Musique.stopPlayerSound(Musique.scala) ~[Musique.class:?]
        at net.machinemuse.powersuits.powermodule.movement.JetPackModule.onPlayerTickInactive(JetPackModule.java:89) ~[JetPackModule.class:?]
        at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$2.apply(PlayerUpdateHandler.scala:51) ~[PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$2.class:?]
        at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$2.apply(PlayerUpdateHandler.scala:50) ~[PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$2.class:?]
        at scala.collection.Iterator$class.foreach(Iterator.scala:743) ~[Iterator$class.class:?]
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1174) ~[AbstractIterator.class:?]
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[IterableLike$class.class:?]
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[AbstractIterable.class:?]
        at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.apply(PlayerUpdateHandler.scala:50) ~[PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.class:?]
        at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.apply(PlayerUpdateHandler.scala:37) ~[PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.class:?]
        at scala.collection.Iterator$class.foreach(Iterator.scala:743) ~[Iterator$class.class:?]
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1174) ~[AbstractIterator.class:?]
```
...

```
[15:59:26] [Server thread/ERROR] [FML]: 15: ASM: net.machinemuse.powersuits.event.PlayerUpdateHandler@196a5e22 onPlayerUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)Ljava/lang/Object;
[15:59:26] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:31179
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:349) ~[mw.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) ~[nh.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20) ~[jf.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/audio/ISound
        at net.machinemuse.numina.sound.Musique.stopPlayerSound(Musique.scala) ~[Musique.class:?]
        at net.machinemuse.powersuits.powermodule.movement.JetPackModule.onPlayerTickInactive(JetPackModule.java:89) ~[JetPackModule.class:?]
        at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$2.apply(PlayerUpdateHandler.scala:51) ~[PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$2.class:?]
        at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$2.apply(PlayerUpdateHandler.scala:50) ~[PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$2.class:?]
        at scala.collection.Iterator$class.foreach(Iterator.scala:743) ~[Iterator$class.class:?]
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1174) ~[AbstractIterator.class:?]
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[IterableLike$class.class:?]
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[AbstractIterable.class:?]
        at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.apply(PlayerUpdateHandler.scala:50) ~[PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.class:?]
        at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.apply(PlayerUpdateHandler.scala:37) ~[PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.class:?]
        at scala.collection.Iterator$class.foreach(Iterator.scala:743) ~[Iterator$class.class:?]
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1174) ~[AbstractIterator.class:?]
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[IterableLike$class.class:?]
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[AbstractIterable.class:?]
        at net.machinemuse.powersuits.event.PlayerUpdateHandler.onPlayerUpdate(PlayerUpdateHandler.scala:37) ~[PlayerUpdateHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_564_PlayerUpdateHandler_onPlayerUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287) ~[ForgeHooks.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560) ~[sv.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) ~[yz.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) ~[mw.class:?]
        ... 10 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.audio.ISound
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
        at net.machinemuse.numina.sound.Musique.stopPlayerSound(Musique.scala) ~[Musique.class:?]
        at net.machinemuse.powersuits.powermodule.movement.JetPackModule.onPlayerTickInactive(JetPackModule.java:89) ~[JetPackModule.class:?]
        at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$2.apply(PlayerUpdateHandler.scala:51) ~[PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$2.class:?]
        at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$2.apply(PlayerUpdateHandler.scala:50) ~[PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$2.class:?]
        at scala.collection.Iterator$class.foreach(Iterator.scala:743) ~[Iterator$class.class:?]
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1174) ~[AbstractIterator.class:?]
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[IterableLike$class.class:?]
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[AbstractIterable.class:?]
        at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.apply(PlayerUpdateHandler.scala:50) ~[PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.class:?]
        at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.apply(PlayerUpdateHandler.scala:37) ~[PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.class:?]
        at scala.collection.Iterator$class.foreach(Iterator.scala:743) ~[Iterator$class.class:?]
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1174) ~[AbstractIterator.class:?]
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[IterableLike$class.class:?]
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[AbstractIterable.class:?]
        at net.machinemuse.powersuits.event.PlayerUpdateHandler.onPlayerUpdate(PlayerUpdateHandler.scala:37) ~[PlayerUpdateHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_564_PlayerUpdateHandler_onPlayerUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287) ~[ForgeHooks.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560) ~[sv.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) ~[yz.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) ~[mw.class:?]
        ... 10 more
Caused by: java.lang.NullPointerException
[15:59:26] [Server thread/INFO]: muszak lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=n
ull, hoverEvent=null}}
[15:59:26] [Server thread/INFO]: muszak left the game
```

**Comment by MachineMuse** [comment]
This should be fixed in build 265?

**Comment by musznik** [comment]
Fixed! thanks for great work!

**Comment by musznik** [comment]
Same bug exist in ModularPowersuits-0.11.0.280.jar

**Comment by MachineMuse** [comment]
Are you sure it's the latest version, and can you post the new crashlog to be extra sure that it's the same error?

**Comment by musznik** [comment]
Log from 0.11.0.280, fixed in 0.11.0.281

```
[22:37:15] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:14226
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:349) ~[mw.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) ~[nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20) ~[jf.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/audio/ISound
	at net.machinemuse.numina.sound.Musique.stopPlayerSound(Musique.scala) ~[Musique.class:?]
	at net.machinemuse.powersuits.powermodule.movement.JetPackModule.onPlayerTickInactive(JetPackModule.java:91) ~[JetPackModule.class:?]
	at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$2.apply(PlayerUpdateHandler.scala:51) ~[PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$2.class:?]
	at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$2.apply(PlayerUpdateHandler.scala:50) ~[PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$2.class:?]
	at scala.collection.Iterator$class.foreach(Iterator.scala:743) ~[Iterator$class.class:?]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1174) ~[AbstractIterator.class:?]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[IterableLike$class.class:?]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[AbstractIterable.class:?]
	at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.apply(PlayerUpdateHandler.scala:50) ~[PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.class:?]
	at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.apply(PlayerUpdateHandler.scala:37) ~[PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.class:?]
	at scala.collection.Iterator$class.foreach(Iterator.scala:743) ~[Iterator$class.class:?]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1174) ~[AbstractIterator.class:?]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[IterableLike$class.class:?]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[AbstractIterable.class:?]
	at net.machinemuse.powersuits.event.PlayerUpdateHandler.onPlayerUpdate(PlayerUpdateHandler.scala:37) ~[PlayerUpdateHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_579_PlayerUpdateHandler_onPlayerUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287) ~[ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560) ~[sv.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) ~[yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) ~[mw.class:?]
	... 10 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.audio.ISound
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at net.machinemuse.numina.sound.Musique.stopPlayerSound(Musique.scala) ~[Musique.class:?]
	at net.machinemuse.powersuits.powermodule.movement.JetPackModule.onPlayerTickInactive(JetPackModule.java:91) ~[JetPackModule.class:?]
	at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$2.apply(PlayerUpdateHandler.scala:51) ~[PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$2.class:?]
	at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$2.apply(PlayerUpdateHandler.scala:50) ~[PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$2.class:?]
	at scala.collection.Iterator$class.foreach(Iterator.scala:743) ~[Iterator$class.class:?]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1174) ~[AbstractIterator.class:?]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[IterableLike$class.class:?]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[AbstractIterable.class:?]
	at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.apply(PlayerUpdateHandler.scala:50) ~[PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.class:?]
	at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.apply(PlayerUpdateHandler.scala:37) ~[PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.class:?]
	at scala.collection.Iterator$class.foreach(Iterator.scala:743) ~[Iterator$class.class:?]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1174) ~[AbstractIterator.class:?]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[IterableLike$class.class:?]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[AbstractIterable.class:?]
	at net.machinemuse.powersuits.event.PlayerUpdateHandler.onPlayerUpdate(PlayerUpdateHandler.scala:37) ~[PlayerUpdateHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_579_PlayerUpdateHandler_onPlayerUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287) ~[ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560) ~[sv.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) ~[yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) ~[mw.class:?]
	... 10 more
Caused by: java.lang.NullPointerException
[22:37:15] [Server thread/INFO]: muszak lost connection:
```

**Comment by MachineMuse** [comment]
but...the only thing that changed in 281 was the .lang file?

**Comment by fblaese** [comment]
Looks like this or a similar bug reappeared in ModularPowersuits-0.11.0.284.jar...

**Comment by lehjr** [comment]
@fblaese Build 284 was accidentally built from an older branch and is essentially an old build with a new number.
