### ISSUE TITLE
Crash on startup on mac

### ISSUE THREAD

**Issue by BryantOh24** [MachineMuse/MachineMusePowersuits#747]
Hi! I'm really sorry to have to bother you with a crash issue considering most of them were resolved way earlier, and this is probably down to my poor knowledge of programming, but could you help me take a look at this crash report?

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 31/12/16 5:18 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: appeng.api.features.IRegistryContainer.wireless()Lappeng/api/features/IWirelessTermRegistry;
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: appeng.api.features.IRegistryContainer.wireless()Lappeng/api/features/IWirelessTermRegistry;
	at net.machinemuse.powersuits.powermodule.tool.TerminalHandler.registerAEHandler(TerminalHandler.java:113)
	at net.machinemuse.powersuits.powermodule.tool.TerminalHandler.registerHandler(TerminalHandler.java:124)
	at net.machinemuse.powersuits.common.ModularPowersuits.load(ModularPowersuits.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.11.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 153885304 bytes (146 MB) / 320622592 bytes (305 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHI	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHI	appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHI	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) 
	UCHI	AIRI{3.0.0-1.7.10} [AIRI] ([1.7.10-10.13.0.1158][3.0.2-1.7.10] AIRI (1).jar) 
	UCHI	AliensVsPredator{3.9.14-1.7.10} [AliensVsPredator] ([1.7.10-10.13.0.1158][3.9.14-1.7.10] AliensVsPredator (1).jar) 
	UCHI	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHI	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) 
	UCHI	DamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.0.jar) 
	UCHI	advancedgenetics{1.5.9} [Advanced Genetics] (advancedgenetics-1.7.10-1.5.9.jar) 
	UCHI	AncientWarfare{2.4.113-beta-MC1.7.10} [Ancient Warfare Core] (ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) 
	UCHI	AncientWarfareAutomation{2.4.113-beta-MC1.7.10} [Ancient Warfare Automation] (ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) 
	UCHI	AncientWarfareNEIPlugin{2.4.113-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) 
	UCHI	AncientWarfareNpc{2.4.113-beta-MC1.7.10} [Ancient Warfare NPCs] (ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) 
	UCHI	AncientWarfareStructure{2.4.113-beta-MC1.7.10} [Ancient Warfare Structures] (ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) 
	UCHI	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
	UCHI	appliedenergistics2{rv1-stable-1} [Applied Energistics 2] (appliedenergistics2-rv1-stable-1.jar) 
	UCHI	BattleTowers{1.5.2} [Battle Towers] (BattleTowers-1.7.10.jar) 
	UCHI	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHI	FoodPlus{3.0rS} [§bFood Plus] (Food-Plus-Mod-1.7.10.jar) 
	UCHI	ironbackpacks{0.5.0} [Iron Backpacks] (Iron Backpacks-1.7.10-1.0.4-universal.jar) 
	UCHI	numina{0.4.1.104} [Numina] (Numina-0.4.1.104.jar) 
	UCHE	powersuits{@VERSION@} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.1.109.jar) 
	UCHI	RentServer{1.0} [�l�2Rent Server Mod] (RentServerMod.jar) 
	UCHI	XaeroMinimap{1.8.5.2} [Xaero's Minimap] (Xaeros_Minimap_1.8.5.2_Forge_1.7.10.jar) 
	UCHI	HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jar) 
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-10.14.73' Renderer: 'Intel(R) HD Graphics 6000'
	AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187

Thanks! :')

**Comment by lehjr** [comment]
**Hint**: you're trying to mix a new version of Modular Powersuits with a 2+ year old version of Applied Energistics. Expect things to go horribly wrong.

**Comment by BryantOh24** [comment]
Ah I see thanks a lot :)
