### ISSUE TITLE
Non-Fatal Server Error 1.10.2 Alpha

### ISSUE THREAD

**Issue by resharp2** [MachineMuse/MachineMusePowersuits#787]
Please note I removed the mod and the error stopped:  (was testing 1.10.2 server)
When walking solid ground the following error kept spamming the server: 
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
	at net.machinemuse.powersuits.event.MovementManager.handleFallEvent(MovementManager.java:72) ~[MovementManager.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_516_MovementManager_handleFallEvent_LivingFallEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingFall(ForgeHooks.java:520) ~[ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.func_180430_e(EntityLivingBase.java:1194) ~[sf.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_180430_e(EntityPlayer.java:1936) ~[zs.class:?]
	at net.minecraft.block.Block.func_180658_a(Block.java:807) ~[akf.class:?]
	at net.minecraft.entity.Entity.func_184231_a(Entity.java:1007) ~[rw.class:?]
	at net.minecraft.entity.EntityLivingBase.func_184231_a(EntityLivingBase.java:205) ~[sf.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71122_b(EntityPlayerMP.java:732) ~[lu.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:517) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(SourceFile:126) ~[iw.class:?]
	at net.minecraft.network.play.client.CPacketPlayer$Position.func_148833_a(SourceFile:57) ~[iw$a.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more

**Comment by lehjr** [comment]
And what version of the mod were you using because that line of code was fixed over a month ago.

**Comment by lehjr** [comment]
Always include version number when filing bug reports. Thanks.

**Comment by lehjr** [comment]
```net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;```
is 
```net.minecraft.entity.player.InventoryPlayer.armorItemInSlot```
which is a client side only method and was replaced in the mod.
https://github.com/MachineMuse/MachineMusePowersuits/blob/1.10.2-Java/src/main/java/net/machinemuse/powersuits/event/MovementManager.java#L72

**Comment by lehjr** [comment]
This was fixed in the second alpha. We've had several more after that. People, before filing any kind of bug report, make sure you are using the latest version.
