### ISSUE TITLE
Error code whenever I try to load the new 1.12.2 version?

### ISSUE THREAD

**Issue by YaBoyEnder** [MachineMuse/MachineMusePowersuits#840]
_The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MachineMuse's Modular Powersuits (powersuits)_

Am I doing something wrong or is this just a bug?

**Comment by lehjr** [comment]
No way of knowing what's happening without a log

**Comment by YaBoyEnder** [comment]
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 8/27/18 12:03 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MachineMuse's Modular Powersuits (powersuits)
Caused by: java.lang.NoSuchMethodError: net.minecraftforge.fml.common.registry.GameRegistry.registerTileEntity(Ljava/lang/Class;Lnet/minecraft/util/ResourceLocation;)V
	at net.machinemuse.powersuits.block.BlockTinkerTable.<init>(BlockTinkerTable.java:46)
	at net.machinemuse.powersuits.common.MPSItems.<clinit>(MPSItems.java:47)
	at net.machinemuse.powersuits.common.proxy.CommonProxy.preInit(CommonProxy.java:40)
	at net.machinemuse.powersuits.common.proxy.ClientProxy.preInit(ClientProxy.java:37)
	at net.machinemuse.powersuits.common.ModularPowersuits.preInit(ModularPowersuits.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 385171464 bytes (367 MB) / 603979776 bytes (576 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2654 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID         | Version        | Source                               | Signature                                |
	|:----- |:---------- |:-------------- |:------------------------------------ |:---------------------------------------- |
	| UCH   | minecraft  | 1.12.2         | minecraft.jar                        | None                                     |
	| UCH   | mcp        | 9.42           | minecraft.jar                        | None                                     |
	| UCH   | FML        | 8.0.99.99      | forge-1.12.2-14.23.2.2654.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge      | 14.23.2.2654   | forge-1.12.2-14.23.2.2654.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | numina     | 1.10.0         | ModularPowersuits-1.12.2-0.1.0.0.jar | None                                     |
	| UCE   | powersuits | 1.12.2-0.1.0.0 | ModularPowersuits-1.12.2-0.1.0.0.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13476 Compatibility Profile Context 22.19.180.1025' Renderer: 'AMD Radeon(TM) R6 Graphics'

**Comment by lehjr** [comment]
Any reason why you're using an outdated version of Forge?

**Comment by lehjr** [comment]
Update Forge and see if that helps.

**Comment by YaBoyEnder** [comment]
That fixed the issue, thanks!
