### ISSUE TITLE
Ticking Player

### ISSUE THREAD

**Issue by dshadowwolf** [MachineMuse/MachineMusePowersuits#844]
During a quick&dirty test when trying to add modifications comparable to what I'd use in 1.10 and prior versions I got a "Ticking Player" crash that seemed to be prefaced by the screen flashing as if the night vision mod was trying to start and not having enough power. [https://gist.github.com/dshadowwolf/6426b4d6b9614116eb0dc5b1d18cb444]("logs/latest.log" is here) - if you need more information, feel free to ask. Looking forward to this finally reaching Release.

**Comment by lehjr** [comment]
Seems the night vision needs a bit more work. The other issue might take a bit more work and is probably related to the compression being used to sync settings between client and player.

**Comment by HideAwayDk** [comment]
Hey :) i got the same crash but whitout night version on, it was night tho and was hited by alot of zombies, (was testing armor :)

Time: 8/28/18 10:44 PM
Description: Ticking player

java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:206)
	at net.minecraft.util.NonNullList.set(SourceFile:49)
	at net.minecraft.entity.player.InventoryPlayer.func_70299_a(InventoryPlayer.java:575)
	at net.machinemuse.powersuits.powermodule.environmental.AutoFeederModule.onPlayerTickActive(AutoFeederModule.java:88)
	at net.machinemuse.powersuits.event.PlayerUpdateHandler.onPlayerUpdate(PlayerUpdateHandler.java:67)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_661_PlayerUpdateHandler_onPlayerUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:567)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

**Comment by lehjr** [comment]
complete logs please, and use pastebin or similar. 
Edit: The crash for the auto feeder should be fixed in the next release.

**Comment by HideAwayDk** [comment]
Sorry lehjr, just thought that it was a small/short crash log related to topic. I normally use pastebin sorry 😊 btw very nice job getting the mod to 1.12! Keep up the good work sir!

**Comment by lehjr** [comment]
Sill needs some work, but it's getting there.

**Comment by lehjr** [comment]
both issues have been fixed in recent alphas
